name: Build

on: [push]

jobs:
  test:
    name: Run tests on macOS 11
    runs-on: macos-11

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactSwift-iOS"
            destination: "platform=iOS Simulator,name=iPhone 12 Pro"
          - scheme: "PactSwift-macOS"
            destination: "arch=x86_64"

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare Tools
        run: |
          Scripts/prepare_build_tools

      - name: Run tests (Xcode)
        run: |
          set -o pipefail && xcodebuild clean test -project PactSwift.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcbeautify

  test_carthage:
    needs: [test]
    name: Test Carthage
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 13.0
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app

      - name: Carthage build
        run: |
          echo "⚠️ Running 'carthage build' with a Xcode 12 workaround script - https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323"
          ./Scripts/carthage_xcode12 build --no-skip-current --platform "ios,macos,tvos"

  after_success:
    needs: [test, test_carthage]
    name: Build demo projects
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build demo projects
        run: |
          echo "⚠️ Skipping: curl -X POST https://api.github.com/repos/surpher/pact-swift-examples/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.PACT_SWIFT_TOKEN }} --data '{\"event_type\":\"PactSwift - ${{ github.event.head_commit.message }}\"}'"
