name: Continuous Integration

on: [pull_request]

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactSwift-iOS"
            destination: "platform=iOS Simulator,name=iPhone 11 Pro"
          - scheme: "PactSwift-macOS"
            destination: "arch=x86_64"

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 11.6
        run: sudo xcode-select -switch /Applications/Xcode_11.6.app

      - name: Prepare Tools
        run: |
          Scripts/prepare_build_tools

      - name: Run tests (Xcode)
        run: |
          set -o pipefail && xcodebuild clean test -project PactSwift.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcbeautify

  test_carthage:
    needs: [test]
    name: Test Carthage
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 11.6
        run: sudo xcode-select -switch /Applications/Xcode_11.6.app

      - name: Carthage build
        run: |
          ./Scripts/carthage_xcode12 build --no-skip-current --platform "ios,macos,tvos"
