name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      release_name:
        description: 'Release name'
        required: true
        default: 'Release'
      dryrun:
        description: 'Dryrun ([-d])'
        required: false

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    name: Release a new version
    runs-on: ubuntu-latest

    steps:
    - name: Config github actor
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Run the release script
      run: |
        ./Scripts/release ${{ github.event.inputs.version }} "${{ github.event.inputs.release_name }}" ${{ github.event.inputs.dryrun }}
      env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
